version: "3.9"

services:
    api:
        build:
            context: ./../
            dockerfile: ./.docker/api/Dockerfile
            target: prod
        deploy:
            replicas: 3
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/api/`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls.certresolver=le"
            - "traefik.http.services.api.loadbalancer.server.port=80"

    frontend:
        build:
            context: ./../
            dockerfile: ./.docker/frontend/Dockerfile
            target: prod
        deploy:
            replicas: 2
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`${PROJECT_URL}`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls.certresolver=le"
            - "traefik.http.services.frontend.loadbalancer.server.port=80"

    traefik:
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:${PROJECT_ENTRY_PORT}"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.le.acme.httpchallenge=true"
            - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.le.acme.email=fabien.zoccola@etu.umontpellier.fr"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - "traefik-le:/letsencrypt"

volumes:
  traefik-le: