version: "3.9"

services:
    api:
        build:
            context: ./../
            dockerfile: ./.docker/api/Dockerfile
            target: prod

    frontend:
        build:
            context: ./../
            dockerfile: ./.docker/frontend/Dockerfile
            target: prod

    traefik:
        command:
            - "--entrypoints.web.address=:${PROJECT_ENTRY_PORT}"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"